name: CD-Extension

on:
  workflow_call:

jobs:
  standalone-executable:
    name: Create a standalone linux executable
    uses: ./.github/workflows/build-executable.yml
    with:
      release-tag: ${{ github.ref_name }}
    permissions:
      contents: write